media: public/media

settings:
  content:
    merge: true

content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter
    view:
      fields: [title, published, date]
      primary: title
      sort: [date]
      order: desc
    fields:
      - { name: title, label: Titel, type: string }
      - { name: date, label: Datum, type: date, options: { time: true } }
      - { name: published, label: Veröffentlicht, type: boolean, default: true }
      - { name: description, label: Beschreibung, type: text }
      - { name: image, label: Bild, type: image }
      - { name: body, label: Inhalt, type: code, options: { language: markdown } }

  - name: about
    label: Über mich
    path: about.md
    type: file
    format: yaml-frontmatter
    fields:
      - { name: title, label: Titel, type: string }
      - { name: body, label: Inhalt, type: rich-text }

  - name: fehlerseite
    label: Fehlerseite (404)
    path: 404.html
    type: file
    format: yaml-frontmatter
    fields:
      - { name: heading, label: Titel, type: string }
      - { name: message, label: Nachricht, type: text }

  - name: site
    label: Website-Einstellungen
    path: _data/site.yml
    type: file
    format: yaml
    fields:
      - { name: title, label: Website-Titel, type: string }
      - { name: description, label: Website-Beschreibung, type: string }
      - { name: lang, label: Sprache, type: string, description: "z.B. de" }
