title: Fälis Blog
description: Mein Blog.
lang: de
date_format: "%d.%m.%Y"
owner:
  name: Fabian Bösiger
  email: boesiger.fabian@outlook.com
social:
  github: fabianboesiger
  twitter: fabianboesiger
  instagram: fabian_boesiger