title: Fabian Bösiger
description: Persönlicher Blog.
lang: de
owner:
  name: Fabian Bösiger
  email: boesiger.fabian@outlook.com
social:
  github: fabianboesiger
  twitter: fabianboesiger
  instagram: fabian_boesiger
  linkedin: fabianboesiger
permalink: /:title
markdown: kramdown
kramdown:
  smart_quotes: ["lsquo", "rsquo", "laquo", "raquo"]
  markdown: kramdown
plugins:
  - jekyll-katex
  - jekyll-compress-images
compress_images:
  images_path: "public/media/**/*.{gif,png,jpg,jpeg,svg}"